// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqfinG_VBA79MFi2jrE4HzGX7oOsba18',
    appId: '1:232643546738:web:12d3561376dbb7ccf37ceb',
    messagingSenderId: '232643546738',
    projectId: 'fir-login1-d5ab1',
    authDomain: 'fir-login1-d5ab1.firebaseapp.com',
    storageBucket: 'fir-login1-d5ab1.appspot.com',
    measurementId: 'G-BZDF0FZMCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBah7q1kEILpDBj81wZ-OPdlMZcGt1jmBo',
    appId: '1:232643546738:android:c22118fc93e1d4c2f37ceb',
    messagingSenderId: '232643546738',
    projectId: 'fir-login1-d5ab1',
    storageBucket: 'fir-login1-d5ab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiBZ4DkLXgx2b6E3HXRid76-5tGqWEBF0',
    appId: '1:232643546738:ios:12f25a5d27c0e2daf37ceb',
    messagingSenderId: '232643546738',
    projectId: 'fir-login1-d5ab1',
    storageBucket: 'fir-login1-d5ab1.appspot.com',
    iosClientId: '232643546738-10rm6a2q585hd882d1s7hiouhcccd7gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiBZ4DkLXgx2b6E3HXRid76-5tGqWEBF0',
    appId: '1:232643546738:ios:12f25a5d27c0e2daf37ceb',
    messagingSenderId: '232643546738',
    projectId: 'fir-login1-d5ab1',
    storageBucket: 'fir-login1-d5ab1.appspot.com',
    iosClientId: '232643546738-10rm6a2q585hd882d1s7hiouhcccd7gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearn',
  );
}
